export { CONFIG, INITIAL_STATE, setInitialState } from "./initial-state"
export type { AnimationRefs } from "./initial-state"
export { createZoomInAnimation, createZoomOutAnimation } from "./zoom-animations"
export { createFolderTransitions } from "./folder-transitions"
export { getContentHeight, calculateTotalDuration, calculateScrollPositionForFolder } from "./utils"
